### ISSUE TITLE
yolov3-tiny training script error: Incompatible shapes: [2,26,26,3,2] vs. [2,52,52,3,2]

### ISSUE THREAD

**Issue by Natashasz** [hunglc007/tensorflow-yolov4-tflite#102]
Hi,

I am getting an incompatible shapes error when training yolov3-tiny. I have downloaded the coco2017 dataset from the official website and changed the paths in data/dataset/val2017.txt. The command I use to invoke the training script is:

```
python train.py --model yolov3-tiny --tiny
```

The full error message:

```
Traceback (most recent call last):
  File "/devel/git_3rd/tensorflow-yolov4-tflite/train.py", line 166, in <module>
    app.run(main)
  File "/devel/git_3rd/tensorflow-yolov4-tflite/env/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/devel/git_3rd/tensorflow-yolov4-tflite/env/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/devel/git_3rd/tensorflow-yolov4-tflite/train.py", line 159, in main
    train_step(image_data, target)
  File "/devel/git_3rd/tensorflow-yolov4-tflite/train.py", line 95, in train_step
    loss_items = compute_loss(pred, conv, target[i][0], target[i][1], STRIDES=STRIDES, NUM_CLASS=NUM_CLASS, IOU_LOSS_THRESH=IOU_LOSS_THRESH, i=i)
  File "/devel/git_3rd/tensorflow-yolov4-tflite/core/yolov4.py", line 270, in compute_loss
    giou = tf.expand_dims(bbox_giou(pred_xywh, label_xywh), axis=-1)
  File "/devel/git_3rd/tensorflow-yolov4-tflite/core/yolov4.py", line 237, in bbox_giou
    left_up = tf.maximum(boxes1[..., :2], boxes2[..., :2])
  File "/devel/git_3rd/tensorflow-yolov4-tflite/env/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 5772, in maximum
    _ops.raise_from_not_ok_status(e, name)
  File "/devel/git_3rd/tensorflow-yolov4-tflite/env/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [2,26,26,3,2] vs. [2,52,52,3,2] [Op:Maximum]
```

Thanks!

**Comment by zateyev** [comment]
Try to set `__C.YOLO.STRIDES = [16, 32, 32]` in config.py

**Comment by Natashasz** [comment]
Thanks for the solution. Now I am getting another error:

```Traceback (most recent call last):
  File "/home/na/git/tensorflow-yolov4-tflite/train.py", line 154, in <module>
    app.run(main)
  File "/home/git/tensorflow-yolov4-tflite/env/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/git/tensorflow-yolov4-tflite/env/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/git/tensorflow-yolov4-tflite/train.py", line 147, in main
    train_step(image_data, target)
  File "/home/git/tensorflow-yolov4-tflite/train.py", line 94, in train_step
    conv, pred = pred_result[i * 2], pred_result[i * 2 + 1]
IndexError: list index out of range```

**Comment by zateyev** [comment]
To train tiny weights you need to change the ranges from 3 to 2 in the `train_step` and `test_step` methods. In addition, you need to change the list of layers to freeze: `'conv2d_93', 'conv2d_101', 'conv2d_109'` to `'conv2d_9', 'conv2d_12'`

**Comment by Natashasz** [comment]
thanks a lot. It is working now
