### ISSUE TITLE
Missing 1 required positional argument: 'model_name'

### ISSUE THREAD

**Issue by 3AXAPOB** [hunglc007/tensorflow-yolov4-tflite#114]
Hi. Trying to convert yolov3-tiny to tflite with

convert_tflite.py --tiny --weights ./data/yolov3-tiny.weights --output ./data/yolov3-tiny.tflite

and gettin this error

Traceback (most recent call last):
  File "convert_tflite.py", line 111, in <module>
    app.run(main)
  File "C:\Users\Сергей\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Сергей\AppData\Local\Programs\Python\Python37\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "convert_tflite.py", line 106, in main
    save_tflite()
  File "convert_tflite.py", line 42, in save_tflite
    utils.load_weights_tiny(model, FLAGS.weights)
TypeError: load_weights_tiny() missing 1 required positional argument: 'model_name'

What i do wrong?

**Comment by bishaldpande** [comment]
The function is currently taking one extra parameter model name that is not passed. 
`load_weights_tiny(model, weights_file, model_name)`
A simple solution would be to update the call as
utils.load_weights_tiny(model, FLAGS.weights, "yolov3")
or could pass the flag model as the parameter
utils.load_weights_tiny(model, FLAGS.weights, FLAGS.model)

**Comment by 3AXAPOB** [comment]
Well i got the same error.

**Comment by hunglc007** [comment]
This issue are fixed in newest code
