### ISSUE TITLE
ValueError: cannot reshape array of size 30868 into shape (256,256,3,3)

### ISSUE THREAD

**Issue by rahuladiga** [hunglc007/tensorflow-yolov4-tflite#115]
Im getting this error while converting yolov4-tiny model to tflite 
Im using tensorflow 2.1
if any other information is required ill provide 

Traceback (most recent call last):
  File "convert_tflite.py", line 111, in <module>
    app.run(main)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python36\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "convert_tflite.py", line 106, in main
    save_tflite()
  File "convert_tflite.py", line 59, in save_tflite
    utils.load_weights(model, FLAGS.weights)
  File "C:\Users\PC\Desktop\tensorflow-yolov4-tflite-master\core\utils.py", line 121, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 30868 into shape (256,256,3,3)

**Comment by hunglc007** [comment]
This issue are fixed in newest code

**Comment by inSight-mk1** [comment]
Still the same issue on yolov4 3-class model.

**Comment by kunalgoyal9** [comment]
same issue in newest code

**Comment by feizhouxiaozhu** [comment]
This problem still exists

**Comment by Ashwin-Ramesh2607** [comment]
@feizhouxiaozhu If you have trained a custom dataset (that has a different number of classes). Then you have to change the class names at `data/classes/coco.names`. This should fix the re-shape issues

**Comment by jenapss** [comment]
@Ashwin-Ramesh2607 Yeap, It works. You just delete all the class names in coco.names and then write your own classes. Thank you!

**Comment by Lorenzo-azar** [comment]
When I changed the classes it skipped the error but i got another error (yolo4 to tf):

Traceback (most recent call last):
  File "save_model.py", line 61, in <module>
    app.run(main)
  File "/home/dgx/anaconda3/envs/yolov4-gpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/dgx/anaconda3/envs/yolov4-gpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 57, in main
    save_tf()
  File "save_model.py", line 50, in save_tf
    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
  File "/home/dgx/Lorenzo/tensorflow-yolov4-tflite/core/utils.py", line 65, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 16119 into shape (21,1024,1,1)

**Comment by Lorenzo-azar** [comment]
When I changed the classes it skipped the error but i got another error (yolo4 to tf):

Traceback (most recent call last):
File "save_model.py", line 61, in
app.run(main)
File "/home/anaconda3/envs/yolov4-gpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
_run_main(main, args)
File "/home/anaconda3/envs/yolov4-gpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
sys.exit(main(argv))
File "save_model.py", line 57, in main
save_tf()
File "save_model.py", line 50, in save_tf
utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
File "/home/tensorflow-yolov4-tflite/core/utils.py", line 65, in load_weights
conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 16119 into shape (21,1024,1,1)

**Comment by Atsaniik** [comment]
> 
> 
> When I changed the classes it skipped the error but i got another error (yolo4 to tf):
> 
> Traceback (most recent call last):
> File "save_model.py", line 61, in
> app.run(main)
> File "/home/anaconda3/envs/yolov4-gpu/lib/python3.7/site-packages/absl/app.py", line 299, in run
> _run_main(main, args)
> File "/home/anaconda3/envs/yolov4-gpu/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
> sys.exit(main(argv))
> File "save_model.py", line 57, in main
> save_tf()
> File "save_model.py", line 50, in save_tf
> utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
> File "/home/tensorflow-yolov4-tflite/core/utils.py", line 65, in load_weights
> conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
> ValueError: cannot reshape array of size 16119 into shape (21,1024,1,1)

change in  config.py
__C.YOLO.ANCHOR_PER_SCALE     = 1.2
__C.YOLO.IOU_LOSS_THRESH      = 0.213
