### ISSUE TITLE
list index out of range yolov4tiny tflite

### ISSUE THREAD

**Issue by vinorth05** [hunglc007/tensorflow-yolov4-tflite#169]
Hello,

When I want to try a demo with tf framework it works, but not with tflite framework (yolov4 tiny), even if the conversion to tflite seemed to be successful :  

`python detect.py --weights ./2_yolo_layers/yolov4-tiny-2l/tflite/yolov4-tiny-2l.tflite --framework tflite --size 416 --model yolov4 --image ./img_1145.jpg --tiny`

I have the following error :   
```
[{'name': 'input_1', 'index': 0, 'shape': array([  1, 416, 416,   3]), 'shape_signature': array([ -1, 416, 416,   3]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
[{'name': 'Identity', 'index': 229, 'shape': array([1, 1, 1]), 'shape_signature': array([-1, -1, -1]), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]
Time model loading:  0.010761737823486328 s
Time pre-processing:  0.19012856483459473 s
Traceback (most recent call last):
  File "detect.py", line 186, in <module>
    app.run(main)
  File "/home/vinorth/.virtualenvs/yolo-tflite/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/vinorth/.virtualenvs/yolo-tflite/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "detect.py", line 85, in main
    boxes, pred_conf = filter_boxes(pred[0], pred[1], score_threshold=0.25, input_shape=tf.constant([input_size, input_size]))
IndexError: list index out of range

If you suspect this is an IPython 7.16.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```

**Comment by vinorth05** [comment]
Hello, I updated my post because I have another error now

**Comment by vinorth05** [comment]
Ok it seemed to work after updating tensorflow to 2.4 version

**Comment by drahmad89** [comment]
Do you mean  tensorflow 2.3?
