### ISSUE TITLE
Detection on android fails

### ISSUE THREAD

**Issue by Freir96** [hunglc007/tensorflow-yolov4-tflite#173]
When I tap the "Camera" button, the camera turns on for about 1 second and then the app goes back to the view from activity_main. Tapping the "Detect" button results in the app closing. Resetting the cache didn't help, and the only change in the code I made was changing the MINIMUM_CONFIDENCE_TF_OD_API.

Detect error:

> Process: org.tensorflow.lite.examples.detection, PID: 17153
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 2535, 4] and a Java object with shape [1, 10647, 4].
        at org.tensorflow.lite.Tensor.throwIfShapeIsIncompatible(Tensor.java:412)
        at org.tensorflow.lite.Tensor.throwIfDataIsIncompatible(Tensor.java:369)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:247)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:166)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:314)
        at org.tensorflow.lite.examples.detection.tflite.YoloV4Classifier.getDetectionsForFull(YoloV4Classifier.java:379)
        at org.tensorflow.lite.examples.detection.tflite.YoloV4Classifier.recognizeImage(YoloV4Classifier.java:531)
        at org.tensorflow.lite.examples.detection.tflite.YoloV4Classifier.recognizeImage(YoloV4Classifier.java:50)
        at org.tensorflow.lite.examples.detection.MainActivity.lambda$null$1$MainActivity(MainActivity.java:52)
        at org.tensorflow.lite.examples.detection.-$$Lambda$MainActivity$OxNL7NrV0ct8jl4zEsUXaD27RnY.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:784)

Camera error: 
> 2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2421)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void org.tensorflow.lite.examples.detection.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:40)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:7383)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1218)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:3250)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:3405)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1994)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:108)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void android.os.Looper.loop() (Looper.java:166)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7523)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void com.android.internal.os.Zygote$MethodAndArgsCaller.run() (Zygote.java:245)
2020-07-28 16:56:35.498 13842-13842/org.tensorflow.lite.examples.detection I/zygote64:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:921)

If this is a problem with the assets, please update the README with an appropriate comment regarding the android project.

**Comment by shahidammer** [comment]
Getting the same error as @Freir96.

**Comment by shahidammer** [comment]
I had the same issue, but when i set the isTiny flag in Yolov4Classifier.java to True it worked for me.

**Comment by cheolgyu** [comment]
It worked fine because I modified YoloV4Classifier.
```
private static boolean isGPU = false;
private static boolean isTiny = true;
```
