### ISSUE TITLE
Error while running save_model.py.  ValueError: Duplicate node name in graph: 'packed'

### ISSUE THREAD

**Issue by mazatov** [hunglc007/tensorflow-yolov4-tflite#178]
I run into this error while running `save_model.py`

```
(tf21) C:\Users\mazat\Documents\Python\Yolov4>python save_model.py --weights ./data/yolov4.weights --output ./checkpoints/yolov4-416 --input_size 416 --model yolov4
2020-07-30 13:06:40.807536: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-07-30 13:06:43.354466: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-07-30 13:06:43.389669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.2GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2020-07-30 13:06:43.401737: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-07-30 13:06:43.438139: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-07-30 13:06:43.468968: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-07-30 13:06:43.481770: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-07-30 13:06:43.520005: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-07-30 13:06:43.540602: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-07-30 13:06:43.608699: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-30 13:06:43.614939: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-07-30 13:06:43.620083: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-07-30 13:06:43.631941: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 2060 computeCapability: 7.5
coreClock: 1.2GHz coreCount: 30 deviceMemorySize: 6.00GiB deviceMemoryBandwidth: 312.97GiB/s
2020-07-30 13:06:43.643695: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-07-30 13:06:43.649284: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll
2020-07-30 13:06:43.653466: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_10.dll
2020-07-30 13:06:43.658547: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_10.dll
2020-07-30 13:06:43.664265: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_10.dll
2020-07-30 13:06:43.669904: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_10.dll
2020-07-30 13:06:43.675966: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-07-30 13:06:43.682745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1697] Adding visible gpu devices: 0
2020-07-30 13:06:44.449296: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-07-30 13:06:44.455022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2020-07-30 13:06:44.457762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2020-07-30 13:06:44.462103: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1241] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4604 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2060, pci bus id: 0000:01:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 10392, in tile
    input, multiples)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1619, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Duplicate node name in graph: 'packed'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "save_model.py", line 58, in <module>
    app.run(main)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 54, in main
    save_tf()
  File "save_model.py", line 36, in save_tf
    output_tensors = decode(fm, FLAGS.input_size // 16, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE, FLAGS.framework)
  File "C:\Users\mazat\Documents\Python\Yolov4\core\yolov4.py", line 169, in decode
    return decode_tf(conv_output, output_size, NUM_CLASS, STRIDES, ANCHORS, i=i, XYSCALE=XYSCALE)
  File "C:\Users\mazat\Documents\Python\Yolov4\core\yolov4.py", line 204, in decode_tf
    xy_grid = tf.tile(tf.expand_dims(xy_grid, axis=0), [batch_size, 1, 1, 3, 1])
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 10397, in tile
    input, multiples, name=name, ctx=_ctx)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 10433, in tile_eager_fallback
    _attr_Tmultiples, (multiples,) = _execute.args_to_matching_eager([multiples], ctx, _dtypes.int32)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\eager\execute.py", line 263, in args_to_matching_eager
    t, dtype, preferred_dtype=default_dtype, ctx=ctx))
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1314, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 1368, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\ops\array_ops.py", line 1304, in _autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py", line 5704, in pack
    "Pack", values=values, axis=axis, name=name)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 742, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 595, in _create_op_internal
    compute_device)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3322, in _create_op_internal
    op_def=op_def)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1786, in __init__
    control_input_ops)
  File "C:\Users\mazat\Anaconda3\envs\tf21\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1622, in _create_c_op
    raise ValueError(str(e))
ValueError: Duplicate node name in graph: 'packed'
```

**Comment by mazatov** [comment]
The issue was with TF version 2.1.0. After installing the newly released 2.3.0, it seems to work.
