### ISSUE TITLE
how to run detect.py with my weight(saved_model.pb)

### ISSUE THREAD

**Issue by nanshenwei** [hunglc007/tensorflow-yolov4-tflite#182]
how to run detect.py with my weight(saved_model.pb)?
I ran with this error:
'''bash
Traceback (most recent call last):
  File "detect.py", line 102, in <module>
    app.run(main)
  File "/home/szturacing/.local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/szturacing/.local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "detect.py", line 90, in main
    score_threshold=FLAGS.score
  File "/home/szturacing/.local/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/szturacing/.local/lib/python3.7/site-packages/tensorflow/python/ops/image_ops_impl.py", line 4335, in combined_non_max_suppression
    score_threshold, pad_per_class, clip_boxes)
  File "/home/szturacing/.local/lib/python3.7/site-packages/tensorflow/python/ops/gen_image_ops.py", line 358, in combined_non_max_suppression
    _ops.raise_from_not_ok_status(e, name)
  File "/home/szturacing/.local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: scores has incompatible shape [Op:CombinedNonMaxSuppression]
'''

help!!!

**Comment by nanshenwei** [comment]
@hunglc007 Sorry for disturbing you. I cann't solve this problem by myself. 😭

**Comment by nanshenwei** [comment]
#160  I ran the detect.py successfully after run saved_model.py which be modified

**Comment by czy9987** [comment]
Excuse me, can you introduce the following operations from training to the final execution of detect.py? I ran into the same problem and need your help.

**Comment by nanshenwei** [comment]
> Excuse me, can you introduce the following operations from training to the final execution of detect.py? I ran into the same problem and need your help.

see #160 ，replace

```python
utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
```
line with
```python
model.load_weights(FLAGS.weights)
```
In save_model.py script. 
Then run save_model.py after training. And the result of save_model.py is what you need in detect.py
I hope it is useful to you。

**Comment by czy9987** [comment]
Thank you very much for your reply, it is really useful.
However, my ultimate goal is to generate a usable .tflite file, but the file obtained by this method is not very good. If I want to get a working tflite file, what should I do?
Thanks again, and hope to reply if you have time!


-------------------------------------------------------------------
**Translation**
十分感谢您的回复，它确实有用。
不过，我的最终目的是希望生成可以使用的.tflite文件，但是这个方法得到的文件不太行，如果我想要得到可以运行的tflite文件，我应该怎么做？
再次感谢，若您有时间的话，希望答复！

您是中国人吗？如果方便的话，我以加您微信吗？
感谢！
微信号：bulibuni

**Comment by czy9987** [comment]
I know where the problem is, thank you very much for your advice
