### ISSUE TITLE
 cannot reshape array of size 595992 into shape (256,384,3,3) when convert yolov4-tiny.weight

### ISSUE THREAD

**Issue by victoriest** [hunglc007/tensorflow-yolov4-tflite#193]
error log:
```
Traceback (most recent call last):
  File "save_model.py", line 59, in <module>
    app.run(main)
  File "E:\_py_env\tf2_env\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "E:\_py_env\tf2_env\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 55, in main
    save_tf()
  File "save_model.py", line 50, in save_tf
    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
  File "E:\tensorflow-yolov4-tflite\core\utils.py", line 64, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 595992 into shape (256,384,3,3)
```

command:
`python save_model.py --weights ./yolov4-tiny-tftf_best.weights --output ./checkpoints/yolov4-tiny-tftf --input_size 416 --model yolov4 --tiny true`

there are 2 classes in my custom dataset, so my .cfg file for darknet:
```
[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=32
subdivisions=16
width=416
height=416
channels=3
momentum=0.9
decay=0.0005
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.00261
burn_in=100
max_batches = 18000
policy=steps
steps=14400,16200
scales=.1,.1

...


[convolutional]
size=1
stride=1
pad=1
filters=24
activation=linear

[yolo]
mask = 3,4,5
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=3
num=6
jitter=.3
scale_x_y = 1.05
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
ignore_thresh = .7
truth_thresh = 1
random=0
resize=1.5
nms_kind=greedynms
beta_nms=0.6

...

[convolutional]
size=1
stride=1
pad=1
filters=24
activation=linear

[yolo]
mask = 0,1,2
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=3
num=6
jitter=.3
scale_x_y = 1.05
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
ignore_thresh = .7
truth_thresh = 1
random=0
resize=1.5
nms_kind=greedynms
beta_nms=0.6
```

Im modified the .names file with 3 classes and` __C.YOLO.CLASSES` in` config.py`

**Comment by 4444borja** [comment]
It seems like https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/147 solves that problem, but I have seen your comment saying that it didn't work for you.
It didn't work for me either, until I opened my cocoCustom.names file to find out I wrote a newline at the beginning of the file. Maybe check that the .names file is in the right format, one class per line.

**Comment by victoriest** [comment]
> It seems like #147 solves that problem, but I have seen your comment saying that it didn't work for you.
> It didn't work for me either, until I opened my cocoCustom.names file to find out I wrote a newline at the beginning of the file. Maybe check that the .names file is in the right format, one class per line.

my .names file is correct. each class per line without empty line.

**Comment by omega-accelr** [comment]
@victoriest , Did you solve this.
I'm also facing the same issue.

**Comment by victoriest** [comment]
> @victoriest , Did you solve this.
> I'm also facing the same issue.

Not yet, I give up converting the yolo model to tf format. 
Im using python api of darknet for instead.

**Comment by david-siagian** [comment]
> > @victoriest , Did you solve this.
> > I'm also facing the same issue.
> 
> Not yet, I give up converting the yolo model to tf format.
> Im using python api of darknet for instead.

Can you convert your custom yolov4 original weight?

**Comment by Alx-AI** [comment]
I am still having this issue, names.custom being read successfully in utils.read_class_names. It fails when my filters, in_dim, k_size, k_size = 33,1024,1,1 and as I am looking for 6 custom objects, I changed the filters in my cfg file (below) to = 33 so leads me to believe that is where the issue arose. 

`
[net]
# Testing
#batch=1
#subdivisions=1
# Training
batch=64
subdivisions=64
width=608
height=608
channels=1
momentum=0.949
decay=0.0005l
angle=0
saturation = 1.5
exposure = 1.5
hue=.1

learning_rate=0.001
burn_in=1000
max_batches = 12000
policy=steps
steps=9600,10800
scales=.1,.1

[convolutional]
size=1
stride=1
pad=1
filters=33
activation=linear


[yolo]
mask = 6,7,8
anchors = 12, 16, 19, 36, 40, 28, 36, 75, 76, 55, 72, 146, 142, 110, 192, 243, 459, 401
classes=6
num=9
jitter=.3
ignore_thresh = .7
truth_thresh = 1
random=1
scale_x_y = 1.05
iou_thresh=0.213
cls_normalizer=1.0
iou_normalizer=0.07
iou_loss=ciou
nms_kind=greedynms
beta_nms=0.6
max_delta=5`

**Comment by cheolgyu** [comment]
I received the same error as this problem, but I can fill in the number of lines in the data/*.name file as much as my class_id by referring to https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/147#issuecomment-669313351
