### ISSUE TITLE
Issues creating quantized int8 tflite model. 

### ISSUE THREAD

**Issue by get2abhi** [hunglc007/tensorflow-yolov4-tflite#207]
Facing issues when creating quantized int8 tflite model. 

```
(base) C02ZL31WLVCF:tensorflow-yolov4-tflite username$ python convert_tflite.py --weights ./checkpoints/yolov4-416 --output ./checkpoints/yolov4-416-int8.tflite --quantize_mode int8 --dataset ./data/dataset/val2017.txt
2020-08-20 14:43:07.291978: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-20 14:43:07.318041: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fe1900751d0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-20 14:43:07.318128: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-20 14:43:24.192804: I tensorflow/core/grappler/devices.cc:78] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
2020-08-20 14:43:24.193880: I tensorflow/core/grappler/clusters/single_machine.cc:356] Starting new session
2020-08-20 14:43:24.378882: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816] Optimization results for grappler item: graph_to_optimize
2020-08-20 14:43:24.378909: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: Graph size after: 2777 nodes (2232), 2811 edges (2265), time = 107.313ms.
2020-08-20 14:43:24.378914: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:818]   function_optimizer: function_optimizer did nothing. time = 3.399ms.
I0820 14:43:31.941138 4650444224 lite.py:624] Using experimental converter: If you encountered a problem please file a bug. You can opt-out by setting experimental_new_converter=False
2020-08-20 14:43:32.890055: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:313] Ignored output_format.
2020-08-20 14:43:32.890070: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:316] Ignored drop_control_dependency.
Traceback (most recent call last):
  File "convert_tflite.py", line 76, in <module>
    app.run(main)
  File "/Users/username/miniconda3/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/username/miniconda3/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "convert_tflite.py", line 71, in main
    save_tflite()
  File "convert_tflite.py", line 45, in save_tflite
    tflite_model = converter.convert()
  File "/Users/username/miniconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 1076, in convert
    return super(TFLiteConverterV2, self).convert()
  File "/Users/username/miniconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 900, in convert
    self).convert(graph_def, input_tensors, output_tensors)
  File "/Users/username/miniconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 638, in convert
    result = self._calibrate_quantize_model(result, **flags)
  File "/Users/username/miniconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 452, in _calibrate_quantize_model
    inference_output_type, allow_float, activations_type)
  File "/Users/username/miniconda3/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 98, in calibrate_and_quantize
    np.dtype(activations_type.as_numpy_dtype()).num)
RuntimeError: Max and min for dynamic tensors should be recorded during calibration: Failed for tensor input_1
Empty min/max for tensor input_1
(base) C02ZL31WLVCF:tensorflow-yolov4-tflite username$

```

**Comment by We-Gold** [comment]
I'm also getting this error. I'm using tensorflow gpu 2.3.0.

**Comment by simondenhaene** [comment]
Hi, I'm also getting this error. Did you find a solution to resolve this problem ? I'm also using tensorflow-gpu 2.3.0.

**Comment by JimBratsos** [comment]
Same error, and there hasn't been a fix for this yet. Please refer to this git https://github.com/hhk7734/tensorflow-yolov4 as it has helped me to obtain a fully int8 quantized model of yolov4-tiny. Other than that, I am trying to figure out how to edit the code to use it for tracking with deepsort

**Comment by mipsan** [comment]
@JimBratsos 
As your recommendation, I try to use that tensorflow-yolov4. However, I could not get **INT8** quantized  model. 
Instead following error messages. 
- TF 2.3.0 
- 3070 

> 2021-05-18 14:42:04.265217: I tensorflow/lite/toco/import_tensorflow.cc:663] Converting unsupported operation: StatelessIf
> 2021-05-18 14:42:04.265264: F tensorflow/lite/toco/import_tensorflow.cc:115] Check failed: attr.value_case() == AttrValue::kType (1 vs. 6)
> Fatal Python error: Aborted
> 
> Current thread 0x00007f8a983c2740 (most recent call first):
>   File "/home/falinux/.virtualenvs/cv4cuda/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 56 in execute
>   File "/home/falinux/.virtualenvs/cv4cuda/lib/python3.6/site-packages/absl/app.py", line 251 in _run_main
>   File "/home/falinux/.virtualenvs/cv4cuda/lib/python3.6/site-packages/absl/app.py", line 303 in run
>   File "/home/falinux/.virtualenvs/cv4cuda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40 in run
>   File "/home/falinux/.virtualenvs/cv4cuda/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93 in main
>   File "/home/falinux/.virtualenvs/cv4cuda/bin/toco_from_protos", line 8 in <module>
> Aborted (core dumped)

Any idea about it?
Thanks

**Comment by maazullah96** [comment]
@mipsan Did you have solved the issue? Anything which can help me out?
[error.txt](https://github.com/hunglc007/tensorflow-yolov4-tflite/files/6823516/error.txt)

**Comment by mipsan** [comment]
@maazullah96 
Did you modified `save_tf`() in the `saved_model.py`?

**Comment by maazullah96** [comment]
I did not have modified anything from saved_model.py

**Comment by mipsan** [comment]
@maazullah96 
Would you refer following link?
https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/214

murdockhou provides how to do it.

**Comment by maazullah96** [comment]
@mipsan 
Did you have tried converting the int8 quantized tflite file to edgepu tflite file?
I have to convert int8 to edgetpu compiled tflite file .

**Comment by mipsan** [comment]
@maazullah96 
I didn't. 
I just need to run the model on the i.mx6.
BTW, any difference betwwen AP to edgetpu tflite?
