### ISSUE TITLE
int8 ERROR when I run convert_tflite.py

### ISSUE THREAD

**Issue by aluds123** [hunglc007/tensorflow-yolov4-tflite#224]
I run this command:
python convert_tflite.py --weights ./checkpoints/yolov4-416 --output ./checkpoints/yolov4-416-int8.tflite --quantize_mode int8 --dataset ./coco_dataset/coco/val207.txt

And occur: 
calibration image /home/soc507/darknet/data/coco/images/val2014//COCO_val2014_000000183693.jpg
calibration image /home/soc507/darknet/data/coco/images/val2014//COCO_val2014_000000150834.jpg
calibration image /home/soc507/darknet/data/coco/images/val2014//COCO_val2014_000000140270.jpg
I0907 13:29:51.712005 139893978974016 convert_tflite.py:48] model saved to: ./checkpoints/yolov3-tiny-int8.tflite
Traceback (most recent call last):
  File "convert_tflite.py", line 76, in <module>
    app.run(main)
  File "/home/aluds/anaconda3/envs/tf230/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/aluds/anaconda3/envs/tf230/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "convert_tflite.py", line 72, in main
    demo()
  File "convert_tflite.py", line 52, in demo
    interpreter.allocate_tensors()
  File "/home/aluds/anaconda3/envs/tf230/lib/python3.5/site-packages/tensorflow/lite/python/interpreter.py", line 243, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/dequantize.cc:61 op_context.input->type == kTfLiteUInt8 || op_context.input->type == kTfLiteInt8 || op_context.input->type == kTfLiteInt16 || op_context.input->type == kTfLiteFloat16 was not true.Node number 64 (DEQUANTIZE) failed to prepare.

Question:
Can someone give me some suggestion?  Thank you.

**Comment by BernardinD** [comment]
Answers to this issue? I'm having the same one

**Comment by drahmad89** [comment]
Answers to this issue? I'm having the same one

**Comment by 4yougames** [comment]
Can someone give me some suggestion? Thank you.

**Comment by joe-tsai-wj** [comment]
A similar issue occurred to me, I use yolov3. Any suggestions?

**Comment by YLTsai0609** [comment]
A similar issue occurred to me, I use yolov3. Any suggestions?

**Comment by istomoya** [comment]
Fix in 
https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/214
worked in converting yolov3-tiny to TF-Lite int8.
I had to comment out lines in save_model.py and add the lines to detect.py.
