### ISSUE TITLE
error when Converting yolov4-tiny darknet weights to tensorflow

### ISSUE THREAD

**Issue by niuwenju** [hunglc007/tensorflow-yolov4-tflite#230]
after runing 
`python save_model.py --weights ./data/yolov4-tiny.weights --output ./checkpoints/yolov4-tiny-416 --input_size 416 --model yolov4 --tiny`
i got error as follows

_Total params: 6,062,814
Trainable params: 6,056,606
Non-trainable params: 6,208
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "save_model.py", line 58, in <module>
    app.run(main)
  File "/home/yons/anaconda3/envs/ocr/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/yons/anaconda3/envs/ocr/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 54, in main
    save_tf()
  File "save_model.py", line 51, in save_tf
    model.save(FLAGS.output)
  File "/home/yons/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1211, in save
    saving.save_model(self, filepath, overwrite, include_optimizer, save_format)
  File "/home/yons/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 113, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/home/yons/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 101, in save_model_to_hdf5
    default=serialization.get_json_type).encode('utf8')
  File "/home/yons/anaconda3/envs/ocr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/yons/anaconda3/envs/ocr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/yons/anaconda3/envs/ocr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/yons/anaconda3/envs/ocr/lib/python3.6/site-packages/tensorflow/python/util/serialization.py", line 69, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', b'\n\tLeakyRelu\x12\tLeakyRelu\x1a"batch_normalization/FusedBatchNorm*\x07\n\x01T\x12\x020\x01*\x0e\n\x05alpha\x12\x05%\xcd\xcc\xcc=')_

**Comment by ahsan44411** [comment]
Hello @niuwenju did you find the solution? I am having the same problem

**Comment by niuwenju** [comment]
try installing tensorflow-gpu==2.3.0
