### ISSUE TITLE
Scaled-YOLOv4 [feature request]

### ISSUE THREAD

**Issue by AlexeyAB** [hunglc007/tensorflow-yolov4-tflite#280]
@hunglc007 Hi,

There are new models: https://github.com/AlexeyAB/darknet/issues/7087
* yolov4-csp
    * cfg:  https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-csp.cfg
    * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-csp.weights

* yolov4x-mish
    * cfg: https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4x-mish.cfg
    * weights: https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4x-mish.weights

![scaled_yolov4_res - копия](https://user-images.githubusercontent.com/4096485/102266206-2c0a1780-3f29-11eb-9871-463eb4a862d8.png)

----

So, if 
```
[yolo]
new_coords=1
```
Then 
![image](https://user-images.githubusercontent.com/4096485/102265775-9cfcff80-3f28-11eb-9a8d-834c903ee812.png)

And `activation=logistic` (sigmoid) is used in `[convolutional]` layer before each `[yolo]` layer https://github.com/AlexeyAB/darknet/blob/a298f94255a20a3198d80ea512755d9e5dddbf02/cfg/yolov4x-mish.cfg#L1408-L1435

**Comment by FUZhanhong** [comment]
scaled-yolov4 in this tensorflow worked? can we train on darket and test in this frameworks?

**Comment by hhk7734** [comment]
https://github.com/hhk7734/tensorflow-yolov4

I tested scaled-yolov4, but not yet commit.
Maybe tomorrow, you can test.

**Comment by AlexeyAB** [comment]
@hhk7734 Hi,
Did you added and tested Scaled-YOLOv4 (yolov4-csp.cfg and yolov4-p7) to https://github.com/hhk7734/tensorflow-yolov4 ?

**Comment by hhk7734** [comment]
@AlexeyAB 
I added only yolov4-csp and yolov4x-mish.

**Comment by aparico** [comment]
> scaled-yolov4 in this tensorflow worked? can we train on darket and test in this frameworks?

I tried it. It didn't work. I had this error:

```
Traceback (most recent call last):
  File "save_model.py", line 58, in <module>
    app.run(main)
  File "C:\Python37\lib\site-packages\absl\app.py", line 303, in run
    _run_main(main, args)
  File "C:\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 54, in main
    save_tf()
  File "save_model.py", line 49, in save_tf
    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
  File "D:\swap\20210319\tensorflow-yolov4-tflite\core\utils.py", line 63, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 3791890 into shape (1024,512,3,3)
```

**Comment by Venketaramana** [comment]
Are there any updates on this? It would be great if the csp Darknet model can be converted for the TensorFlow framework.

**Comment by hibaalqaysi** [comment]
> I tried it. It didn't work. I had this error:
> 
> ```
> Traceback (most recent call last):
>   File "save_model.py", line 58, in <module>
>     app.run(main)
>   File "C:\Python37\lib\site-packages\absl\app.py", line 303, in run
>     _run_main(main, args)
>   File "C:\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "save_model.py", line 54, in main
>     save_tf()
>   File "save_model.py", line 49, in save_tf
>     utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
>   File "D:\swap\20210319\tensorflow-yolov4-tflite\core\utils.py", line 63, in load_weights
>     conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
> ValueError: cannot reshape array of size 3791890 into shape (1024,512,3,3)
> ```

Hi @aparico, did you fix that problem please? I'm having the same issue.

**Comment by aparico** [comment]
> > I tried it. It didn't work. I had this error:
> > ```
> > Traceback (most recent call last):
> >   File "save_model.py", line 58, in <module>
> >     app.run(main)
> >   File "C:\Python37\lib\site-packages\absl\app.py", line 303, in run
> >     _run_main(main, args)
> >   File "C:\Python37\lib\site-packages\absl\app.py", line 251, in _run_main
> >     sys.exit(main(argv))
> >   File "save_model.py", line 54, in main
> >     save_tf()
> >   File "save_model.py", line 49, in save_tf
> >     utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
> >   File "D:\swap\20210319\tensorflow-yolov4-tflite\core\utils.py", line 63, in load_weights
> >     conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
> > ValueError: cannot reshape array of size 3791890 into shape (1024,512,3,3)
> > ```
> 
> Hi @aparico, did you fix that problem please? I'm having the same issue.

@hibaalqaysi I tried doing [this solution](https://stackoverflow.com/a/66721135/14461262) instead

**Comment by akashAD98** [comment]
After converting yolo-mish.weight into .pb format its not working ?? i want to convert yolov4-csp/mish.weights into both .pb & .pth format.please have look on this features.i m really grateful to you.

**Comment by akashAD98** [comment]
onxx : https://github.com/onnx/onnx/issues/3475#issuecomment-842427505
