### ISSUE TITLE
Not able to run benchmark.py with pretrained model

### ISSUE THREAD

**Issue by dh0d** [hunglc007/tensorflow-yolov4-tflite#310]
I'm trying to run benchmark with pretrained model YOLOv4-Mish-416 from this page: https://github.com/AlexeyAB/darknet/wiki/YOLOv4-model-zoo

After run:
python benchmarks.py --size 416 --model yolov4 --weights ./data/yolov4-mish-416.weights

I got error:
```
Traceback (most recent call last):
  File "benchmarks.py", line 132, in <module>
    app.run(main)
  File "/home/hc/repo/python_yolo/lib/python3.6/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/hc/repo/python_yolo/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "benchmarks.py", line 65, in main
    bbox_tensor = decode(fm, NUM_CLASS, i)
TypeError: decode() missing 3 required positional arguments: 'STRIDES', 'ANCHORS', and 'i'
```

**Comment by linmeon** [comment]
same error

**Comment by dalhorde** [comment]
Same error as well.
In the code there is only few parameters for the decode function. 
If you look at the function `decode()`, it calls another function : `decode_tf()`.
You can see at the line 27 and 29 of `benchmark.py` that the variables `STRIDES` and `ANCHORS` are defined.
Therefor, they are not used in the function. If you add them at line 65, there is always a missing argument, `i`.
Because the constructor of the YOLOv4 class return this : `return [conv_sbbox, conv_mbbox, conv_lbbox]` and there is an `enumerate(feature_map)` in the loop, we need to find out how to include `output_size`.
For now, my new line 65 is : `bbox_tensor = decode(fm, NUM_CLASS, STRIDES, ANCHORS, i)`

**Comment by han-sang-jun** [comment]
I do: bbox_tensor = decode(fm, fm.shape[1], NUM_CLASS, STRIDES, ANCHORS, i)

**Comment by MediniAmani** [comment]
any solutions for this Error ?

**Comment by Emmanuel-Messulam** [comment]
I fixed it using:

    decode(fm, cfg.TRAIN.INPUT_SIZE // 16, NUM_CLASS, STRIDES, ANCHORS, i)

instead of

    decode(fm, NUM_CLASS, i)

**Comment by MediniAmani** [comment]
Thank you.
