### ISSUE TITLE
How to detect with trained weights? i'm getting an error

### ISSUE THREAD

**Issue by joeanderson995** [hunglc007/tensorflow-yolov4-tflite#33]
After train in checkpoints folder i have file: yolov4.data-00001-of-00002 and trying to detect with command: ```python detect.py --weights=checkpoints/yolov4.data-00001-of-00002 --framework tf --size 416 --image f:/test.jpg``` but getting an error:
 ```
Traceback (most recent call last):
  File "detect.py", line 105, in <module>
    app.run(main)
  File "C:\Users\123\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\123\AppData\Local\Programs\Python\Python38\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "detect.py", line 73, in main
    utils.load_weights(model, FLAGS.weights)
  File "F:\test_task\YOLOs\tensorflow-yolov4-tflite-master\core\utils.py", line 114, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 24571 into shape (24,1024,1,1)

```
So what i'm doing wrong?

**Comment by jzoker** [comment]
Only darknet .weights was supported right now. Will update for tensorflow save models

**Comment by ShihuaiXu** [comment]
now it supports? @jzoker
