### ISSUE TITLE
 OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'rectangle'

### ISSUE THREAD

**Issue by phykurox** [hunglc007/tensorflow-yolov4-tflite#368]
After saving the model, running detection with 'python detect.py --weights ./checkpoints/yolov4-416 --size 416 --model yolov4 --images ./data/images/kite.jpg' give me an error of:
`
    cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'rectangle'
    > Overload resolution failed:
    >  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
    >  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
    >  - Can't parse 'rec'. Expected sequence length 4, got 2
    >  - Can't parse 'rec'. Expected sequence length 4, got 2
`

**Comment by lazarjovanovicnissatech** [comment]
Try to change following lines in core/utils.py as defined below:

Line 152 -> c1, c2 = (int(coor[1]), int(coor[0])), (int(coor[3]), int(coor[2]))
Line 159 -> cv2.rectangle(image, c1, (int(np.float32(c3[0])), int(np.float32(c3[1]))), bbox_color, -1)
Line 161 -> cv2.putText(image, bbox_mess, (c1[0], int(np.float32(c1[1] - 2))), cv2.FONT_HERSHEY_SIMPLEX,
                        fontScale, (0, 0, 0), bbox_thick // 2, lineType=cv2.LINE_AA)

**Comment by phykurox** [comment]
@lazarjovanovicnissatech Thank you, it worked! :D

**Comment by MilanceS14** [comment]
@lazarjovanovicnissatech Thank you! I have been struggling with this as well.

**Comment by ahmethamzakaya** [comment]
@lazarjovanovicnissatech same problem occured in windows 10.  You are great, i think repo should be updated

**Comment by Alejoqe** [comment]
Hi everybody, i'm new in this topics, i dont undertand where can i find that lines to fix the error. Anybody can help me please?? step by step im a rookie, jajaja!  Tks so much!

**Comment by lazarjovanovic** [comment]
> Hi everybody, i'm new in this topics, i dont undertand where can i find that lines to fix the error. Anybody can help me please?? step by step im a rookie, jajaja! Tks so much!

So, you have at first to clone the repo. Then, inside, there is a directory called core where you have to enter. Inside core directory, there is a file called utils.py. Open this file in any editor that counts line in code and modify specified lines from above.

**Comment by barkhaneum** [comment]
That's a really cool solution thanks :)

**Comment by syedfaiqueali** [comment]
> So, you have at first to clone the repo. Then, inside, there is a directory called core where you have to enter. Inside core directory, there is a file called utils.py. Open this file in any editor that counts line in code and modify specified lines from above.

Hi everyone, getting the same error in juypter notebook. Unable to locate `utils.py` inside my installed cv2 package through anaconda. It would be great if someone could help me out in locating the files `utils.py`.
Thanks!

**Comment by Ashwin4514** [comment]
How should we tackle this problem on Kaggle?

**Comment by Hamed-Aghapanah** [comment]
I think Line is not be installed with pip install cv2 on conda 
so  use these :
conda install -c conda-forge opencv 
conda install -c conda-forge/label/gcc7 opencv
conda install -c conda-forge/label/broken opencv
conda install -c conda-forge/label/cf201901 opencv
conda install -c conda-forge/label/cf202003 opencv

**Comment by AliciaD2018** [comment]
Hi, I have this problem to:
   frame = cv2.rectangle(frame, int(x1, y1) + box_h, int(x2, y1), color, 5)
TypeError: only integer tensors of a single element can be converted to an index
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback
OpenCV: FFMPEG: tag 0x47504a4d/'MJPG' is not supported with codec id 7 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'

**Comment by AliciaD2018** [comment]
solved

**Comment by Devparihar5** [comment]
I face this problem how to solve  and where the repo for cloning::
Traceback (most recent call last):
  File "E:\Computer Vision\day2\string.py", line 13, in <module>
    color,thickness,cv2.LINE_AA)
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - rectangle() takes at most 7 arguments (8 given)
>  - rectangle() takes at most 7 arguments (8 given)
>  - rectangle() takes at most 6 arguments (8 given)
>  - rectangle() takes at most 6 arguments (8 given)

**Comment by courtney-ann** [comment]
> How do I find the core/utils.py file?

**Comment by plrlz2** [comment]
Probably it depends on the version of the dependencies, but if you face those type issues, just put `coor = coor.astype(int)` right after `coor[3] = int(coor[3] * image_w)` in L145 and remove the float casts `np.float32` in L159 and L161. 
```
cv2.rectangle(image, c1, c3, bbox_color, -1) 
cv2.putText(image, bbox_mess, (c1[0], (c1[1] - 2)), cv2.FONT_HERSHEY_SIMPLEX,
            fontScale, (0, 0, 0), bbox_thick // 2, lineType=cv2.LINE_AA)
```

**Comment by kumar1838** [comment]
Traceback (most recent call last):
  File "D:\voter task\yolo-coco-data\yolo_object_detection.py", line 70, in <module>
    img=cv2.rectangle(img, (x, y), (x + w, y + h), color, 2)
cv2.error: OpenCV(4.5.4) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'rec'. Expected sequence length 4, got 2

**Comment by kumar1838** [comment]
Im facing this issue kindly help me out

**Comment by anjith101** [comment]
> Try to change following lines in core/utils.py as defined below:
> 
> Line 152 -> c1, c2 = (int(coor[1]), int(coor[0])), (int(coor[3]), int(coor[2])) Line 159 -> cv2.rectangle(image, c1, (int(np.float32(c3[0])), int(np.float32(c3[1]))), bbox_color, -1) Line 161 -> cv2.putText(image, bbox_mess, (c1[0], int(np.float32(c1[1] - 2))), cv2.FONT_HERSHEY_SIMPLEX, fontScale, (0, 0, 0), bbox_thick // 2, lineType=cv2.LINE_AA)

Thank you it worked :)

**Comment by apnaik77** [comment]
how to solve the error 
error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'dilate'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'

**Comment by KishanMishra1** [comment]
For the code:
` image = cv2.resize(img, (1800, 1800))
    alpha=1.5
    beta=20
    new_image=cv2.addWeighted(image,alpha,np.zeros(image.shape, image.dtype),0,beta)
    cv2.imwrite("new",new_image)`

This error coming ..

cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'

**Comment by Esogbue** [comment]
I'm also having issues as well it's giving this error:
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'CascadeClassifier'
>Overload resolution failed:
> - Can't convert object to 'str' for 'filename'

**Comment by AndrewMarines** [comment]
> Try to change following lines in core/utils.py as defined below:
> 
> Line 152 -> c1, c2 = (int(coor[1]), int(coor[0])), (int(coor[3]), int(coor[2])) Line 159 -> cv2.rectangle(image, c1, (int(np.float32(c3[0])), int(np.float32(c3[1]))), bbox_color, -1) Line 161 -> cv2.putText(image, bbox_mess, (c1[0], int(np.float32(c1[1] - 2))), cv2.FONT_HERSHEY_SIMPLEX, fontScale, (0, 0, 0), bbox_thick // 2, lineType=cv2.LINE_AA)

I think lines have changed cause this is for example what line 152 looks like
![immagine](https://user-images.githubusercontent.com/34715958/181267637-3be7a86a-a54e-467d-9e42-f87d835332b0.png)

**Comment by MSRafid** [comment]
hello, where to find the 'utils.py'?

**Comment by ryonaya** [comment]
> hello, where to find the 'utils.py'?

inside the "core" folder

**Comment by hamza233** [comment]
Following worked for me:
`img = cv2.rectangle(img.copy(), (x,y), (x2,y2), (0,0,255), 2)`

**Comment by enesagu** [comment]
I have a problem: Output names: ['output', 'onnx::Shape_425', 'onnx::Shape_440', 'onnx::Shape_455']
Input shape: ['batch', 3, 'width', 'height']
Traceback (most recent call last):
  File "/home/tractus/Desktop/example/python/python1/tractus/yolov8-parseq-lpr_lasted/square.py", line 45, in <module>
    resized = cv2.resize(image_rgb, (input_width, input_height))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type
>  - Can't parse 'dsize'. Sequence item with index 0 has a wrong type
