### ISSUE TITLE
Apply yolov5 to Android

### ISSUE THREAD

**Issue by parksy2109** [hunglc007/tensorflow-yolov4-tflite#380]
I would like to see the results by putting the yolov5 model in Android. 
So, after converting .pt to .tflite, I put it in the TF_OD_API_MODEL_FILE path, but I get an error.
how can I use yolov5 model to use android?

The error message is as follows

Thanks

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.tensorflow.lite.examples.detection, PID: 26144
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.lite.examples.detection/org.tensorflow.lite.examples.detection.MainActivity}: java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
    
    Registration failed.
    
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3779)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3943)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2276)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8424)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
    
    Registration failed.
    
        at org.tensorflow.lite.examples.detection.tflite.YoloV4Classifier.create(YoloV4Classifier.java:111)
        at org.tensorflow.lite.examples.detection.MainActivity.initBox(MainActivity.java:122)
        at org.tensorflow.lite.examples.detection.MainActivity.onCreate(MainActivity.java:68)
        at android.app.Activity.performCreate(Activity.java:8171)
        at android.app.Activity.performCreate(Activity.java:8155)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3752)
        	... 11 more
     Caused by: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Didn't find op for builtin opcode 'RESIZE_NEAREST_NEIGHBOR' version '3'
    
    Registration failed.
    
        at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
        at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:72)
        at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:63)
        at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:237)
        at org.tensorflow.lite.examples.detection.tflite.YoloV4Classifier.create(YoloV4Classifier.java:109)
        	... 17 more

**Comment by thaingoc2604** [comment]
@parky2109 Have you solved this problem yet?
