### ISSUE TITLE
ValueError: Got unexpected field names: ['max_batch_size']

### ISSUE THREAD

**Issue by Stevenisawesome520** [hunglc007/tensorflow-yolov4-tflite#401]
I am facing the following error:
`Traceback (most recent call last):
  File "convert_trt.py", line 100, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "convert_trt.py", line 96, in main
    save_trt()
  File "convert_trt.py", line 58, in save_trt
    max_batch_size=8)
  File "/usr/lib/python3.7/collections/__init__.py", line 416, in _replace
    raise ValueError(f'Got unexpected field names: {list(kwds)!r}')
ValueError: Got unexpected field names: ['max_batch_size']`

is there anyone having the same problem?
Would you please solve this problem?
Thank you.

**Comment by edwardchang0112-nctu** [comment]
Any ideas on this issue? I got the same issue.

**Comment by UygarUsta** [comment]
Install required tensorflow version (pip install tensorflow==2.3.0rc0).Also do not forget that libnvinfer6 should also be installed.

**Comment by maxlotz** [comment]
This guide suggests that when using trt.TrtGraphConverterV2 instead of trt.TrtGraphConverter, it does not have a max_batch_size argument
https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#tf-trt-api-20

**Comment by sumaiya69** [comment]
I'm facing the same issue. How did you solve the error?
