### ISSUE TITLE
what is problem? aborted?

### ISSUE THREAD

**Issue by ubix12** [hunglc007/tensorflow-yolov4-tflite#56]
2020-05-24 20:35:58.385069: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-05-24 20:35:58.397870: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-24 20:35:58.403026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]      0
2020-05-24 20:35:58.407979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] 0:   N
2020-05-24 20:36:02.141023: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:814] Optimization results for grappler item: graph_to_optimize
2020-05-24 20:36:02.146717: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 1356 nodes (-541), 3100 edges (-541), time = 1700.85303ms.
2020-05-24 20:36:02.154191: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:816]   constant_folding: Graph size after: 1356 nodes (0), 3100 edges (0), time = 610.245ms.
Traceback (most recent call last):
  File "convert_tflite.py", line 111, in <module>
    app.run(main)
  File "C:\Users\Park\anaconda3\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\Users\Park\anaconda3\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "convert_tflite.py", line 106, in main
    save_tflite()
  File "convert_tflite.py", line 80, in save_tflite
    tflite_model = converter.convert()
  File "C:\Users\Park\anaconda3\lib\site-packages\tensorflow_core\lite\python\lite.py", line 464, in convert
    **converter_kwargs)
  File "C:\Users\Park\anaconda3\lib\site-packages\tensorflow_core\lite\python\convert.py", line 457, in toco_convert_impl
    enable_mlir_converter=enable_mlir_converter)
  File "C:\Users\Park\anaconda3\lib\site-packages\tensorflow_core\lite\python\convert.py", line 203, in toco_convert_protos
    raise ConverterError("See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: See console for info.
2020-05-24 20:39:16.123023: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
2020-05-24 20:39:20.043565: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 1121 operators, 1900 arrays (0 quantized)
2020-05-24 20:39:20.064185: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 1121 operators, 1900 arrays (0 quantized)
2020-05-24 20:39:20.772842: F tensorflow/lite/toco/graph_transformations/propagate_fixed_sizes.cc:460] Check failed: input_flat_size == RequiredBufferSizeForShape(output_shape) (73008 vs. 689520)Input cannot be reshaped to requested dimensions for Reshape op with output "model/tf_op_layer_Reshape/Reshape". Are your input shapes correct?
Fatal Python error: Aborted

Current thread 0x00001250 (most recent call first):
  File "c:\users\park\anaconda3\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 56 in execute
  File "c:\users\park\anaconda3\lib\site-packages\absl\app.py", line 250 in _run_main
  File "c:\users\park\anaconda3\lib\site-packages\absl\app.py", line 299 in run
  File "c:\users\park\anaconda3\lib\site-packages\tensorflow_core\python\platform\app.py", line 40 in run
  File "c:\users\park\anaconda3\lib\site-packages\tensorflow_core\lite\toco\python\toco_from_protos.py", line 93 in main
  File "C:\Users\Park\anaconda3\Scripts\toco_from_protos.exe\__main__.py", line 7 in <module>
  File "c:\users\park\anaconda3\lib\runpy.py", line 85 in _run_code
  File "c:\users\park\anaconda3\lib\runpy.py", line 193 in _run_module_as_main

I think custom model is not converted.

I tried normal yolov4.weights then it works well. But I want to convert my custom weights.

**Comment by ubix12** [comment]
It was problem about convert_tflite.py NUM_CLASSES. Thanks :)
