### ISSUE TITLE
Error when converting to full int8 tflite - Max and min for dynamic tensors should be recorded during calibration

### ISSUE THREAD

**Issue by vinorth05** [hunglc007/tensorflow-yolov4-tflite#69]
Hello everyone,

When I convert my yolo v4 model to tflite and float 16, I have no problem.

However, I have the following error when trying to convert to full_int8: 

Traceback (most recent call last):
  File "convert_tflite.py", line 111, in <module>
    app.run(main)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "convert_tflite.py", line 106, in main
    save_tflite()
  File "convert_tflite.py", line 80, in save_tflite
    tflite_model = converter.convert()
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 469, in convert
    self.experimental_new_quantizer)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/tensorflow_core/lite/python/lite.py", line 243, in _calibrate_quantize_model
    inference_output_type, allow_float, enable_mlir_quantizer)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/calibrator.py", line 81, in calibrate_and_quantize
    enable_mlir_quantizer)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/tensorflow_core/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 115, in QuantizeModel
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_QuantizeModel(self, *args)
RuntimeError: Max and min for dynamic tensors should be recorded during calibration

If you suspect this is an IPython 7.15.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Here is my command:
python convert_tflite.py --weights /home/vinorth/darknet/saved_models/yolo_v4_full_dataset_74000_epochs/yolo-obj_best.weights --output ./data/output/tflite_models/yolov4-int8.tflite --quantize_mode full_int8 --dataset /home/vinorth/darknet/data/train_full_dataset.txt

Thank you for your help

**Comment by sterlingrpi** [comment]
Does your train_full_dataset.txt file contain hard coded paths to each of your training images? As well as the bounding boxes and classes?

**Comment by vinorth05** [comment]
Thank you very much it worked now:

However, now I have a problem when trying to compile to edge_tpu, in fact most of operations are not supported for Edge TPU as you can see here : 

edgetpu_compiler ./data/output/tflite_models/yolov4-full_int8.tflite

Edge TPU Compiler version 2.1.302470888

Model compiled successfully in 495 ms.

Input model: ./data/output/tflite_models/yolov4-full_int8.tflite
Input size: 62.26MiB
Output model: yolov4-full_int8_edgetpu.tflite
Output size: 62.17MiB
On-chip memory used for caching model parameters: 3.00KiB
On-chip memory remaining for caching model parameters: 7.84MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 961
Operation log: yolov4-full_int8_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 1
Number of operations that will run on CPU: 960
See the operation log file for individual operation details.

[yolov4-full_int8_edgetpu.log](https://github.com/hunglc007/tensorflow-yolov4-tflite/files/4711112/yolov4-full_int8_edgetpu.log)

Is there a way to bypass this problem?

Thank you

**Comment by a-rich** [comment]
@vinorth05 I've tried `tensorflow==2.1.0` and `tensorflow==2.20` the former yields the same result (only 1 of 961 ops on Edge)

The latter was 1 of 886 because `ValueError: Didn't find op for builtin opcode 'LEAKY_RELU' version '2'`

**Comment by sterlingrpi** [comment]
@vinorth05 and @a-rich I am interested in running this model on a TPU as well. I previously had trouble converting to full int 8 because leaky_relu is not supported. We changed this operation to regular relu, retrained, and it seems to have worked (for full int8, have not tried TPU compiling).

You can try to follow what we have done https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/53, or I can give you one of my tflite files with regular relu. I might also try TPU compiling myself. Is it still a web compiler?

**Comment by vinorth05** [comment]
Yes, I am interested in getting your tflite files as well as your cfg file for training your yolo files. 
Did you try for yolov3 or v4? I am also interested in doing the same for SSD if anyone tried it before.
Yes, it is still a web compiler with "edgetpu_compiler" command.

**Comment by a-rich** [comment]
@sterlingrpi when you converted your standard RELU model `--quantization full_int8` what was the ratio of ops converted for Edgetpu?

When I try with LEAKY_RELU ops, I get

```
Input model: yolov4_2.tflite
Input size: 62.67MiB
Output model: yolov4_2_edgetpu.tflite
Output size: 62.58MiB
On-chip memory used for caching model parameters: 3.00KiB
On-chip memory remaining for caching model parameters: 7.84MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 962
Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 1
Number of operations that will run on CPU: 962
```

**Comment by a-rich** [comment]
@sterlingrpi I did as you did in #53 i.e. changing
`conv = tf.nn.leaky_relu(conv, alpha=0.1)`
to
`conv = tf.nn.relu(conv)`

and converted using `--quantization full_int8`...

When I run through the `edgetpu_compiler` I get:

```
Edge TPU Compiler version 2.1.302470888

Model compiled successfully in 677 ms.

Input model: yolov4_RELU.tflite
Input size: 62.66MiB
Output model: yolov4_RELU_edgetpu.tflite
Output size: 62.56MiB
On-chip memory used for caching model parameters: 3.00KiB
On-chip memory remaining for caching model parameters: 7.84MiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 849
Operation log: yolov4_RELU_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 1
Number of operations that will run on CPU: 848
See the operation log file for individual operation details.
```

and the log shows:

```
Edge TPU Compiler version 2.1.302470888
Input: yolov4_RELU.tflite
Output: yolov4_RELU_edgetpu.tflite

Operator                       Count      Status

LOGISTIC                       6          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
EXP                            72         Operation is working on an unsupported data type
MAX_POOL_2D                    3          More than one subgraph is not supported
QUANTIZE                       15         More than one subgraph is not supported
QUANTIZE                       154        Operation is otherwise supported, but not mapped due to some unspecified limitation
MUL                            72         More than one subgraph is not supported
RESHAPE                        3          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
TANH                           72         More than one subgraph is not supported
ADD                            95         More than one subgraph is not supported
RESIZE_NEAREST_NEIGHBOR        2          More than one subgraph is not supported
PAD                            7          More than one subgraph is not supported
CONCATENATION                  10         More than one subgraph is not supported
CONCATENATION                  3          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
CONV_2D                        109        More than one subgraph is not supported
CONV_2D                        1          Mapped to Edge TPU
SPLIT_V                        3          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
DEQUANTIZE                     144        Operation is working on an unsupported data type
DEQUANTIZE                     6          Tensor has unsupported rank (up to 3 innermost dimensions mapped)
LOG                            72         Operation is working on an unsupported data type
```

Seems like a lot more operation substitutions are required to get YOLOv4 running on the Edgetpu.

**Comment by sterlingrpi** [comment]
@a-rich nice work! sorry I was slow getting back to you. I cannot find the web compiler. Seems like it's a download and install? I'll have to set that up. https://coral.ai/docs/edgetpu/compiler/

Good work on trying the changes I made. Like I said I had to do that to get full int8 to work because leaky_relu was not a supported operation. We may have to substitute more operations. Usually the relu is included in the 2D convolution. I wonder if that is what the TPU compiler is designed to use.

Is there a list of TPU supported operations? Have you gotten the TPU compiler to work for other tflite files?

**Comment by vinorth05** [comment]
Here are the supported operations: https://coral.ai/docs/edgetpu/models-intro/#supported-operations

However, as you can see in our log files, even some supported operations in this link are not supported for us just because "they have more than one subgraph" or because they are "not mapped due to some unspecified limitation". So I wonder how we need to do quantization-aware training for yolo.

**Comment by sterlingrpi** [comment]
after some googling I am considering jumping ship for mobilenet SSD. It works similar to YOLO (single shot detection) but is better supported by tensorflow and TPU. And is designed/benchmarked for mobile.

**Comment by sterlingrpi** [comment]
Can someone link me to the TPU web compiler? I can't find it. Only the one I have to download and it requires a Linux system.

I have been working in a SSD repo (https://github.com/ChunML/ssd-tf2). I made my own model using the TF functional API, and not a subclass so it is supported by tflite. I defined every layer so I can be sure all the layers are supported. Before I go through annotating all the data and doing a thorough training I want to be sure it converts to TPU.

**Comment by sterlingrpi** [comment]
Managed to compile the TPU files with a linux VM. Wasn't a big deal at all. Looks like even the custom model I wrote in SSD isn't fully supported by TPU (42 out of 52). But still better than the YOLO model with regular Relu (22 out of 47). Question now is how to determine which of the operations were not supported?

![image](https://user-images.githubusercontent.com/22107859/84549034-02033e80-acd5-11ea-939d-324f5f1ee940.png)

**Comment by sterlingrpi** [comment]
ok cool. so the TPU compiler prints a nifty log file showing which ops go where. Looks like all the convolution (contains relu) and max pooling is done on the TPU. So should be pretty zippy. I'll try it on the TPU next.

**Comment by vinorth05** [comment]
Hi @sterlingrpi thank you for your ideas. Can you please tell us in which file did you define every layer? 
And maybe even share this file? so I could also try for my MobileNetv3-SSD model.

**Comment by sterlingrpi** [comment]
@vinorth05 I am working off of this repo https://github.com/ChunML/ssd-tf2. Right now the changes I made are kind of a mess and not fully vetted. When it's a  little bit better I plan to branch it off and share it.

**Comment by sterlingrpi** [comment]
@vinorth05 the whole repo isn't ready to be submitted. But here is a VGG16 SSD model I defined using the tensorflow functional API.

def get_VGG16_SSD_300(image_size, num_classes):
    inputs = tf.keras.Input(shape=(image_size[0], image_size[1], image_size[2]))
    x = layers.Conv2D(64, 3, padding='same', activation='relu')(inputs)
    x = layers.Conv2D(64, 3, padding='same', activation='relu')(x)
    x = layers.MaxPool2D(2, 2, padding='same')(x)
    x = layers.Conv2D(128, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(128, 3, padding='same', activation='relu')(x)
    x = layers.MaxPool2D(2, 2, padding='same')(x)
    x = layers.Conv2D(256, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(256, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(256, 3, padding='same', activation='relu')(x)
    x = layers.MaxPool2D(2, 2, padding='same')(x)
    x = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    block_4_features = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    x = layers.MaxPool2D(2, 2, padding='same')(block_4_features)
    x = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    output_vgg16 = layers.Conv2D(512, 3, padding='same', activation='relu')(x)

    x = layers.BatchNormalization(beta_initializer='glorot_uniform', gamma_initializer='glorot_uniform')(block_4_features)
    conf4 = layers.Conv2D(4 * num_classes, kernel_size=3, padding='same')(x)  # conf 4th block0
    conf4 = layers.Reshape((conf4.shape[1]*conf4.shape[2]*conf4.shape[3]//num_classes, num_classes))(conf4)
    loc4 = layers.Conv2D(4 * 4, kernel_size=3, padding='same')(x)  # loc 4th block
    loc4 = layers.Reshape((loc4.shape[1]*loc4.shape[2]*loc4.shape[3]//4, 4))(loc4)

    x = layers.MaxPool2D(3, 1, padding='same')(output_vgg16)
    x = layers.Conv2D(1024, 3, padding='same', dilation_rate=6, activation='relu')(x)
    x = layers.Conv2D(1024, 1, padding='same', activation='relu')(x)
    conf7 = layers.Conv2D(6 * num_classes, kernel_size=3, padding='same')(x)  # conf 7th block
    conf7 = layers.Reshape((conf7.shape[1] * conf7.shape[2] * conf7.shape[3] // num_classes, num_classes))(conf7)
    loc7 = layers.Conv2D(6 * 4, kernel_size=3, padding='same')(x)  # loc 7th block
    loc7 = layers.Reshape((loc7.shape[1]*loc7.shape[2]*loc7.shape[3]//4, 4))(loc7)

    x = layers.Conv2D(256, 1, activation='relu')(x)  # extra_layers 8th block output shape: B, 512, 10, 10
    x = layers.Conv2D(512, 3, strides=2, padding='same', activation='relu')(x)
    conf8 = layers.Conv2D(6 * num_classes, kernel_size=3, padding='same')(x)  # conf 8th block
    conf8 = layers.Reshape((conf8.shape[1] * conf8.shape[2] * conf8.shape[3] // num_classes, num_classes))(conf8)
    loc8 = layers.Conv2D(6 * 4, kernel_size=3, padding='same')(x)  # loc 8th block
    loc8 = layers.Reshape((loc8.shape[1] * loc8.shape[2] * loc8.shape[3] // 4, 4))(loc8)

    x = layers.Conv2D(128, 1, activation='relu')(x)  # extra_layers 9th block output shape: B, 256, 5, 5
    x = layers.Conv2D(256, 3, strides=2, padding='same', activation='relu')(x)
    conf9 = layers.Conv2D(6 * num_classes, kernel_size=3, padding='same')(x)  # conf 9th block
    conf9 = layers.Reshape((conf9.shape[1] * conf9.shape[2] * conf9.shape[3] // num_classes, num_classes))(conf9)
    loc9 = layers.Conv2D(6 * 4, kernel_size=3, padding='same')(x)  # loc 9th block
    loc9 = layers.Reshape((loc9.shape[1] * loc9.shape[2] * loc9.shape[3] // 4, 4))(loc9)

    x = layers.Conv2D(128, 1, activation='relu')(x)  # extra_layers 10th block output shape: B, 256, 3, 3
    x = layers.Conv2D(256, 3, activation='relu')(x)
    conf10 = layers.Conv2D(4 * num_classes, kernel_size=3, padding='same')(x)  # conf 10th block
    conf10 = layers.Reshape((conf10.shape[1] * conf10.shape[2] * conf10.shape[3] // num_classes, num_classes))(conf10)
    loc10 = layers.Conv2D(4 * 4, kernel_size=3, padding='same')(x)  # loc 10th block
    loc10 = layers.Reshape((loc10.shape[1] * loc10.shape[2] * loc10.shape[3] // 4, 4))(loc10)

    x = layers.Conv2D(128, 1, activation='relu')(x)  # extra_layers 11th block output shape: B, 256, 1, 1
    x = layers.Conv2D(256, 3, activation='relu')(x)
    conf11 = layers.Conv2D(4 * num_classes, kernel_size=3, padding='same')(x)  # conf 11th block
    conf11 = layers.Reshape((conf11.shape[1] * conf11.shape[2] * conf11.shape[3] // num_classes, num_classes))(conf11)
    loc11 = layers.Conv2D(4 * 4, kernel_size=3, padding='same')(x)  # loc 11th block
    loc11 = layers.Reshape((loc11.shape[1] * loc11.shape[2] * loc11.shape[3] // 4, 4))(loc11)

    confs = layers.concatenate([conf4, conf7, conf8, conf9, conf10, conf11], axis=1)
    locs = layers.concatenate([loc4, loc7, loc8, loc9, loc10, loc11], axis=1)
    model = tf.keras.Model(inputs=inputs, outputs=[confs, locs])

    model_VGG16 = VGG16(weights='imagenet')
    for i in range(18):
        model.get_layer(index=i).set_weights(model_VGG16.get_layer(index=i).get_weights())

    return model

**Comment by sinclairnick** [comment]
@sterlingrpi the TF repo has [pre-compiled MobileNetSSD models](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), use them

**Comment by sterlingrpi** [comment]
@sinclairnick thank you. But I have a custom dataset. I'm actually having much better success with image segmentation now using a custom loss function that weights the classes

**Comment by sinclairnick** [comment]
@sterlingrpi ah ok, no worries then

**Comment by raryanpur** [comment]
Is anyone able to share an integer quantized yolov3.tflite or yolov4.tflite model trained on the coco 80 dataset and compiled for the edge TPU? Have been trying to use the the scripts in this repo to get a quantized model of either version; however,  getting some strange Python abort errors (see #166) when trying to do the quantization. Ultimately am looking to train on my own dataset, but trying to get something working as a baseline to build from.

**Comment by hhk7734** [comment]
@raryanpur 
Hi~
https://github.com/hhk7734/tensorflow-yolov4
I tested yolov4-tiny-relu on edgetpu. But not optimized yet.

**Comment by raryanpur** [comment]
@hhk7734 great! Thanks for sharing. What fps were you able to achieve with the TPU? Were you able to get all of the TF operators to compile for the Edge TPU, or just a subset?

**Comment by hhk7734** [comment]
@raryanpur 
Failed to compile the whole. Some sequence or operations are not compiled. The part that failed compilation was replaced by numpy.

```shell
Edge TPU Compiler version 14.1.317412892

Model compiled successfully in 566 ms.

Input model: test/yolov4-relu-tiny-int8.tflite
Input size: 5.74MiB
Output model: yolov4-relu-tiny-int8_edgetpu.tflite
Output size: 5.86MiB
On-chip memory used for caching model parameters: 5.69MiB
On-chip memory remaining for caching model parameters: 448.75KiB
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 1
Total number of operations: 51
Operation log: yolov4-relu-tiny-int8_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 46
Number of operations that will run on CPU: 5
See the operation log file for individual operation details.
```

TPU consume 55 ~ 60ms, other is 35 ~ 40ms. FPS is 10~11.

**Comment by rockmosi** [comment]
@hhk7734 Awesome! Thanks for info. BTW how do you get the yolov4-relu-tiny or how do you make /yolov4-relu-tiny?

**Comment by hhk7734** [comment]
I forked this repo and changed some code.
Using the below script, yolov4-relu-tiny.weights was created.
But mAP50 is 25%. so I'm trying to figure out why mAP is low.

```shell
python3 -m pip install yolov4 -U
```

```python
from tensorflow.keras import callbacks, optimizers
from yolov4.tf import SaveWeightsCallback, YOLOv4

yolo = YOLOv4(tiny=True)

yolo.classes = "/content/drive/My Drive/Hard_Soft/NN/coco/coco.names"

yolo.input_size = 608
yolo.batch_size = 64
yolo.subdivision = 32

initial_epoch = 0

yolo.make_model(activation1="relu")
yolo.load_weights(
    "/content/drive/My Drive/Hard_Soft/NN/yolov4-tiny.conv.29, weights_type="yolo"
)

train_data_set = yolo.load_dataset("/content/drive/My Drive/Hard_Soft/NN/coco/train2017.txt")
val_data_set = yolo.load_dataset("/content/drive/My Drive/Hard_Soft/NN/coco/val2017.txt", training=False)

epochs = 15000
lr = 1e-4

optimizer = optimizers.Adam(learning_rate=lr)
yolo.compile(optimizer=optimizer, loss_iou_type="ciou")

def lr_scheduler(epoch):
    if epoch < 500 + initial_epoch:
        return ((epoch - initial_epoch + 1) / 500) * lr
    elif epoch < int(epochs * 0.8):
        return lr
    elif epoch < int(epochs * 0.9):
        return lr * 0.1
    else:
        return lr * 0.01

yolo.fit(
    train_data_set,
    epochs=epochs,
    callbacks=[
        callbacks.LearningRateScheduler(lr_scheduler),
        callbacks.TerminateOnNaN(),
        SaveWeightsCallback(
            yolo=yolo, dir_path="/content/drive/My Drive/Hard_Soft/NN/trained",
            weights_type="yolo", epoch_per_save=500
        ),
    ],
    validation_data=val_data_set,
    validation_steps=100,
    validation_freq=100,
    initial_epoch=initial_epoch,
    verbose=2,
)
```
