### ISSUE TITLE
App was getting crash when i open it

### ISSUE THREAD

**Issue by gowthami77** [hunglc007/tensorflow-yolov4-tflite#70]
here is the error report . Please help me to resolve this error.

org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL **EXCEPTION:** main
    **Process: org.tensorflow.lite.examples.detection, PID: 12970
    _java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.lite.examples.detection/org.tensorflow.lite.examples.detection.MainActivity}_:** java.lang.RuntimeException: java.io.FileNotFoundException: yolov4full.tflite
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
     Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: yolov4full.tflite
        at org.tensorflow.lite.examples.detection.tflite.YoloV4Classifier.create(YoloV4Classifier.java:114)
        at org.tensorflow.lite.examples.detection.MainActivity.initBox(MainActivity.java:122)
        at org.tensorflow.lite.examples.detection.MainActivity.onCreate(MainActivity.java:68)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7811) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068) 
     Caused by: java.io.FileNotFoundException: yolov4full.tflite
        at android.content.res.AssetManager.nativeOpenAssetFd(Native Method)
        at android.content.res.AssetManager.openFd(AssetManager.java:899)
        at org.tensorflow.lite.examples.detection.env.Utils.loadModelFile(Utils.java:31)
        at org.tensorflow.lite.examples.detection.tflite.YoloV4Classifier.create(YoloV4Classifier.java:112)
        at org.tensorflow.lite.examples.detection.MainActivity.initBox(MainActivity.java:122) 
        at org.tensorflow.lite.examples.detection.MainActivity.onCreate(MainActivity.java:68) 
        at android.app.Activity.performCreate(Activity.java:7955) 
        at android.app.Activity.performCreate(Activity.java:7944) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7811)

**Comment by in-die-nibelungen** [comment]
I have no experience of running android app on this repo, but as far as see the log, all you have to do is to prepare `yolov4full.tflite`.

>  java.lang.RuntimeException: java.io.FileNotFoundException: yolov4full.tflite

#47 would help you.

**Comment by EuphoriaCelestial** [comment]
convert model to .tflite and put it in asset folder, rebuild the app and you should be able to run
