### ISSUE TITLE
failed to read all data

### ISSUE THREAD

**Issue by vinorth05** [hunglc007/tensorflow-yolov4-tflite#82]
Hello everyone,

I have no problem when I convert to tflite when converting yolov4 models or yolo v3 tiny models (with 2 yolo-layers).

However, when I want to convert yolo v3 tiny-prn models or yolo v3 tiny models (with 3 yolo-layers) to tflite models, I have the following errors:

- for yolo tiny with 3 yolo-layers: 

`Traceback (most recent call last):                                                                                                                                                                                 
  File "convert_tflite.py", line 115, in <module>                                                                                                                                                                  
    app.run(main)                                                                                                                                                                                                  
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/absl/app.py", line 299, in run                                                                                                      
    _run_main(main, args)                                                                                                                                                                                          
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main                                                                                                
    sys.exit(main(argv))                                                                                                                                                                                           
  File "convert_tflite.py", line 110, in main                                                                                                                                                                      
    save_tflite()                                                                                                                                                                                                  
  File "convert_tflite.py", line 45, in save_tflite                                                                                                                                                                
    utils.load_weights_tiny(model, FLAGS.weights)                                                                                                                                                                  
  File "/home/vinorth/tensorflow-yolov4-tflite/core/utils.py", line 45, in load_weights_tiny                                                                                                                       
    assert len(wf.read()) == 0, 'failed to read all data'                                                                                                                                                          
AssertionError: failed to read all data`

- for yolo tiny-prn: 

`Traceback (most recent call last):
  File "convert_tflite.py", line 115, in <module>
    app.run(main)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/vinorth/anaconda3/envs/yolov4-tflite/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "convert_tflite.py", line 110, in main
    save_tflite()
  File "convert_tflite.py", line 45, in save_tflite
    utils.load_weights_tiny(model, FLAGS.weights)
  File "/home/vinorth/tensorflow-yolov4-tflite/core/utils.py", line 37, in load_weights_tiny
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 3271862 into shape (1024,512,3,3)`

Is it possible to support yolo3 models even if we add or remove layers? Thank you in advance

**Comment by sterlingrpi** [comment]
The whole repo is not ready to be pushed. But here is a VGG16 SSD model I defined using the tensorflow functional API.

def get_VGG16_SSD_300(image_size, num_classes):
    inputs = tf.keras.Input(shape=(image_size[0], image_size[1], image_size[2]))
    x = layers.Conv2D(64, 3, padding='same', activation='relu')(inputs)
    x = layers.Conv2D(64, 3, padding='same', activation='relu')(x)
    x = layers.MaxPool2D(2, 2, padding='same')(x)
    x = layers.Conv2D(128, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(128, 3, padding='same', activation='relu')(x)
    x = layers.MaxPool2D(2, 2, padding='same')(x)
    x = layers.Conv2D(256, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(256, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(256, 3, padding='same', activation='relu')(x)
    x = layers.MaxPool2D(2, 2, padding='same')(x)
    x = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    block_4_features = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    x = layers.MaxPool2D(2, 2, padding='same')(block_4_features)
    x = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    x = layers.Conv2D(512, 3, padding='same', activation='relu')(x)
    output_vgg16 = layers.Conv2D(512, 3, padding='same', activation='relu')(x)

    x = layers.BatchNormalization(beta_initializer='glorot_uniform', gamma_initializer='glorot_uniform')(block_4_features)
    conf4 = layers.Conv2D(4 * num_classes, kernel_size=3, padding='same')(x)  # conf 4th block0
    conf4 = layers.Reshape((conf4.shape[1]*conf4.shape[2]*conf4.shape[3]//num_classes, num_classes))(conf4)
    loc4 = layers.Conv2D(4 * 4, kernel_size=3, padding='same')(x)  # loc 4th block
    loc4 = layers.Reshape((loc4.shape[1]*loc4.shape[2]*loc4.shape[3]//4, 4))(loc4)

    x = layers.MaxPool2D(3, 1, padding='same')(output_vgg16)
    x = layers.Conv2D(1024, 3, padding='same', dilation_rate=6, activation='relu')(x)
    x = layers.Conv2D(1024, 1, padding='same', activation='relu')(x)
    conf7 = layers.Conv2D(6 * num_classes, kernel_size=3, padding='same')(x)  # conf 7th block
    conf7 = layers.Reshape((conf7.shape[1] * conf7.shape[2] * conf7.shape[3] // num_classes, num_classes))(conf7)
    loc7 = layers.Conv2D(6 * 4, kernel_size=3, padding='same')(x)  # loc 7th block
    loc7 = layers.Reshape((loc7.shape[1]*loc7.shape[2]*loc7.shape[3]//4, 4))(loc7)

    x = layers.Conv2D(256, 1, activation='relu')(x)  # extra_layers 8th block output shape: B, 512, 10, 10
    x = layers.Conv2D(512, 3, strides=2, padding='same', activation='relu')(x)
    conf8 = layers.Conv2D(6 * num_classes, kernel_size=3, padding='same')(x)  # conf 8th block
    conf8 = layers.Reshape((conf8.shape[1] * conf8.shape[2] * conf8.shape[3] // num_classes, num_classes))(conf8)
    loc8 = layers.Conv2D(6 * 4, kernel_size=3, padding='same')(x)  # loc 8th block
    loc8 = layers.Reshape((loc8.shape[1] * loc8.shape[2] * loc8.shape[3] // 4, 4))(loc8)

    x = layers.Conv2D(128, 1, activation='relu')(x)  # extra_layers 9th block output shape: B, 256, 5, 5
    x = layers.Conv2D(256, 3, strides=2, padding='same', activation='relu')(x)
    conf9 = layers.Conv2D(6 * num_classes, kernel_size=3, padding='same')(x)  # conf 9th block
    conf9 = layers.Reshape((conf9.shape[1] * conf9.shape[2] * conf9.shape[3] // num_classes, num_classes))(conf9)
    loc9 = layers.Conv2D(6 * 4, kernel_size=3, padding='same')(x)  # loc 9th block
    loc9 = layers.Reshape((loc9.shape[1] * loc9.shape[2] * loc9.shape[3] // 4, 4))(loc9)

    x = layers.Conv2D(128, 1, activation='relu')(x)  # extra_layers 10th block output shape: B, 256, 3, 3
    x = layers.Conv2D(256, 3, activation='relu')(x)
    conf10 = layers.Conv2D(4 * num_classes, kernel_size=3, padding='same')(x)  # conf 10th block
    conf10 = layers.Reshape((conf10.shape[1] * conf10.shape[2] * conf10.shape[3] // num_classes, num_classes))(conf10)
    loc10 = layers.Conv2D(4 * 4, kernel_size=3, padding='same')(x)  # loc 10th block
    loc10 = layers.Reshape((loc10.shape[1] * loc10.shape[2] * loc10.shape[3] // 4, 4))(loc10)

    x = layers.Conv2D(128, 1, activation='relu')(x)  # extra_layers 11th block output shape: B, 256, 1, 1
    x = layers.Conv2D(256, 3, activation='relu')(x)
    conf11 = layers.Conv2D(4 * num_classes, kernel_size=3, padding='same')(x)  # conf 11th block
    conf11 = layers.Reshape((conf11.shape[1] * conf11.shape[2] * conf11.shape[3] // num_classes, num_classes))(conf11)
    loc11 = layers.Conv2D(4 * 4, kernel_size=3, padding='same')(x)  # loc 11th block
    loc11 = layers.Reshape((loc11.shape[1] * loc11.shape[2] * loc11.shape[3] // 4, 4))(loc11)

    confs = layers.concatenate([conf4, conf7, conf8, conf9, conf10, conf11], axis=1)
    locs = layers.concatenate([loc4, loc7, loc8, loc9, loc10, loc11], axis=1)
    model = tf.keras.Model(inputs=inputs, outputs=[confs, locs])

    model_VGG16 = VGG16(weights='imagenet')
    for i in range(18):
        model.get_layer(index=i).set_weights(model_VGG16.get_layer(index=i).get_weights())

    return model

**Comment by molimat** [comment]
Yes, it is. But you should change your .\core\config.py file to your new class.names file
as in this example.
`__C.YOLO.CLASSES              = "./data/classes/custom.names"`

Of course, this custom.names file has the same classes that Iused to generate the weight file from darknet training.
This should be ok.
