### ISSUE TITLE
.weights转tf时报错

### ISSUE THREAD

**Issue by tosonw** [hunglc007/tensorflow-yolov4-tflite#92]
我使用AlexeyAB的darknet框架的tolov4.weights转tf时，报出如下错误：

Traceback (most recent call last):
  File "save_model.py", line 55, in <module>
    app.run(main)
  File "/home/toson/.local/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/toson/.local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 51, in main
    save_tf()
  File "save_model.py", line 48, in save_tf
    model.save(FLAGS.output)
  File "/home/toson/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1211, in save
    saving.save_model(self, filepath, overwrite, include_optimizer, save_format)
  File "/home/toson/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/save.py", line 113, in save_model
    model, filepath, overwrite, include_optimizer)
  File "/home/toson/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 101, in save_model_to_hdf5
    default=serialization.get_json_type).encode('utf8')
  File "/home/toson/miniconda3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/toson/miniconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/toson/miniconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/toson/.local/lib/python3.6/site-packages/tensorflow/python/util/serialization.py", line 69, in get_json_type
    raise TypeError('Not JSON Serializable:', obj)
TypeError: ('Not JSON Serializable:', b'\n\x03add\x12\x03Add\x1a\x0clambda_3/mul\x1a\x0clambda_5/mul*\x07\n\x01T\x12\x020\x01')

请问需要怎么修改？？

**Comment by luccao** [comment]
this problem I also meet now

**Comment by luccao** [comment]
on tensorflow 1.14 python3.6
